openapi: 3.0.0

info:
  title: MyLive Service
  version: "4"
  description: |
    De MyLive service geeft de status van een specifieke bezoeker weer. De MyLive informatie kan worden opgevraagd
    via de QR-Coode in Room Service:

    1. QR-Code redirect naar `https://{customer}.door2doc.net/app/mobile/mylive.html?code={code}`. Deze link mag gedeeld worden met derden.
    2. Vraag de huidige status op via `/services/v3/mylive/status/{code}`. Deze code mag gedeeld worden met derden.
  license:
    name: Door2doc
    url: https://www.door2doc.com


servers:
  - url: https://{customer}.door2doc.net
    variables:
      customer:
        default: demo
        enum:
          - demo
          - qa-demo

security:
  - {}

components:
  schemas:
    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          example: "stuff went wrong"

    Status:
      type: object
      required:
        - locatie
        - status
        - behandelruimtes
        - bezet
        - stappen
        - onderzoeken
      properties:
        locatie:
          type: string
          description: Code van de locatie waar deze bezoeker zich bevindt
        status:
          $ref: '#/components/schemas/BezoekerStatus'
        wachtend:
          type: number
          description: Aantal wachtenden (op dezelfde arts) voor deze patiënt. Alleen aanwezig indien dit veld getoond moet worden.
          example: 3
        in-behandeling:
          type: number
          description: Aantal patiënten in behandeling bij dezelfde arts. Alleen aanwezig indien dit veld getoond moet worden.
          example: 3
        wachttijd:
          type: number
          description: Verwachte wachttijd in minuten. Alaleen aanwezig indien dit veld getoond moet worden.
          example: 72
        verblijftijd:
          type: number
          description: Verwachte verblijftijd in minuten. Alleen aanwezig indien dit veld getoond moet worden.
          example: 84
        behandelruimtes:
          type: number
          description: Aantal behandelruimtes beschikbaar.
          example: 11
        bezet:
          type: number
          description: Aantal behandelruimtes in gebruik.
          example: 8
        vrij:
          type: number
          description: Aantal behandelruimtes vrij
          example: 3
        stappen:
          type: array
          items:
            $ref: '#/components/schemas/Stap'
          description: Stappenplan voor deze patient.
      example:
        {
          "locatie": "ams",
          "status": "wacht-op-arts",
          "wachtend": 5,
          "wachttijd": 75,
          "behandelruimtes": 11,
          "bezet": 8,
          "vrij": 3,
          "stappen": [
            {
              "fase": "aankomst",
              "tijdstip": "2020-04-03T23:00:07.023+02:00",
              "afgerond": true
            },
            {
              "fase": "triage",
              "tijdstip": "2020-04-04T00:05:00.000+02:00",
              "afgerond": true
            },
            {
              "fase": "behandelruimte",
              "tijdstip": "2020-04-04T00:05:00.000+02:00",
              "afgerond": true
            },
            {
              "fase": "onderzoek",
              "current": true,
              "orders": [
                {
                  "type": "rontgen",
                  "naam": "Röntgenfoto",
                  "afgerond": false,
                  "tijdstip": "2020-04-04T00:05:00.000+02:00",
                }
              ]
            },
            {
              "fase": "arts",
            },
            {
              "fase": "beslissing"
            },
            {
              "fase": "arts_klaar"
            },
            {
              "fase": "vertrek"
            },
          ]
        }

    BezoekerStatus:
      type: string
      enum:
        - wacht-op-arts
        - wacht-op-beslissing
        - wacht-op-vertrek
        - vertrokken
      description: |
        Status van de bezoeker.
        * wacht-op-arts: Wachtend op arts
        * wacht-op-beslissing: Gezien door een arts, maar nog geen beslissing
        * wacht-op-vertrek: Arts heeft beslissing genomen, patient nog niet vertrokken
        * vertrokken: Patient is vertrokken

    Stap:
      type: object
      required:
        - fase
      properties:
        fase:
          $ref: '#/components/schemas/Fase'
        current:
          type: boolean
          description: "Geeft aan of dit de 'huidige' stap is. Indien afwezig, te beschouwen als `false`. Let op: er kunnen meerdere 'huidige' stappen zijn."
        afgerond:
          type: boolean
          description: Geeft aan of deze stap is afgerond. Indien afwezig, te beschouwen als `false`.
        tijdstip:
          type: string
          format: date-time
          description: Tijdstip waarop deze stap is afgerond; afwezig indien deze stap nog niet is afgerond.
        orders:
          type: array
          items:
            $ref: '#/components/schemas/Order'
          description: Lopende en afgeronde onderzoeken binnen deze stap.


    Fase:
      type: string
      enum:
        - aankomst
        - triage
        - behandelruimte
        - arts
        - onderzoek
        - beslissing
        - arts_klaar
        - vertrek
      description: Fase in de aanwezigheid van de patient

    OrderType:
      type: string
      enum:
        - lab
        - icc
        - rontgen
      description: Soort order

    Order:
      type: object
      required:
        - type
        - naam
        - afgerond
        - tijdstip
      properties:
        type:
          $ref: '#/components/schemas/OrderType'
        naam:
          type: string
          description: Naam van dit specifieke onderzoek
          example: "Röntgenfoto"
        afgerond:
          type: boolean
          description: Geeft aan of dit onderzoek is afgerond.
        tijdstip:
          type: string
          format: date-time
          description: Tijdstip waarop dit onderzoek is begonnen
      description: Diagnostische order, gebruikt tijdens de onderzoek fase.
      example: |
        {
          "type": "rontgen",
          "naam": "Röntgenfoto",
          "afgerond": false,
          "tijdstip": "2020-04-04T00:05:00.000+02:00",
        }

paths:
  /public/v4/mylive/status:
    get:
      summary: Vraag de huidige status op voor een specifieke bezoeker.
      operationId: getStatus
      tags:
        - 'Public'
      parameters:
        - name: code
          in: query
          required: true
          description: De code uit de QR Code.
          schema:
            type: string
      responses:
        401:
          description: De code is ongeldig.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        410:
          description: De code is verlopen.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        200:
          description: De huidige status voor deze bezoeker.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
